### ISSUE TITLE
Right click places two blocks

### ISSUE THREAD

**Issue by dhalenok** [traverseda/PyCraft#78] opened 2016-04-28 16:36 UTC
Last merge request (#72) seems to have messed something up.
Right click places two blocks instead of one, I don't know if that was intended or not.
Does anyone else have the same behavior?

**Comment by nitori** [comment] 2016-04-28 16:53
`on_mouse_press` is called twice, as it seems.

https://github.com/traverseda/pycraft/blob/master/pycraft/window.py#L53-L56

**Comment by dhalenok** [comment] 2016-04-29 00:00
Can you confirm that the issue was fixed?

**Comment by traverseda** [comment] 2016-04-29 09:24
I _just_ merged in a PR for it. #79

**Closed as completed by traverseda** 2016-04-29 09:24 UTC

**Comment by nitori** [comment] 2016-04-29 16:07
So, has it actually been confirmed this issue was fixed? I certainly have not tried it. And my suggestion above was merely a guess.

**Comment by traverseda** [comment] 2016-04-29 16:22
I think so. It takes multiple clicks to remove a block because of the durability system, which is still very much a WiP.

But I'm not seeing anything that would indicate multiple blocks getting placed. I'll look into it during the weekend.
